# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'RCPilot' do
  # React Native Maps dependencies
  pod 'react-native-maps/Google', :path => '../node_modules/react-native-maps'

  # React Native Sensors dependencies
  pod 'RNSensors', :path => '../node_modules/react-native-sensors'

  config = use_native_modules!
  use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'RNBootSplash', :path => '../node_modules/react-native-bootsplash'

  # React Native Maps dependencies
  # The following line is only needed if building on an Apple silicon Mac without rosetta.
  # pod 'Google-Maps-iOS-Utils', :git => 'https://github.com/Simon-TechForm/google-maps-ios-utils.git', :branch => 'feat/support-apple-silicon'
  # pod 'react-native-google-maps', :path => '../node_modules/react-native-maps'
  
  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # Workaround for Xcode 26 beta consteval error in fmt library.
    # Patch fmt/base.h to disable consteval which breaks with Apple clang in Xcode 26.
    fmt_base = File.join(__dir__, 'Pods/fmt/include/fmt/base.h')
    if File.exist?(fmt_base)
      content = File.read(fmt_base)
      unless content.include?('Patched for Xcode 26')
        content.gsub!('#  define FMT_CONSTEVAL consteval', '#  define FMT_CONSTEVAL // Patched for Xcode 26')
        File.write(fmt_base, content)
      end
    end

    # Workaround for VisionCamera UIWindowScene availability error in Xcode 26.
    installer.pods_project.targets.each do |target|
      if target.name == 'VisionCamera'
        target.build_configurations.each do |config|
          config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
        end
      end
    end
  end

end
